version: '3'
services:
  app:
    image: prophius-social-media-api:latest
    ports:
      - "8080:8080"
    volumes:
      - ./your-java-app-config:/app/config
    environment:
      - JAVA_OPTS=-Xmx512m
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=prophiussocialsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data